debian/tmp/usr/bin/amor
debian/tmp/usr/include/AmorIface.h
debian/tmp/usr/share/apps/amor
debian/tmp/usr/share/applications/tde/amor.desktop
debian/tmp/usr/share/doc/tde/HTML/en/amor/*.bz2
debian/tmp/usr/share/doc/tde/HTML/en/amor/*.docbook
debian/tmp/usr/share/doc/tde/HTML/en/amor/*.png
debian/tmp/usr/share/doc/tde/HTML/en/amor/common
debian/tmp/usr/share/icons/hicolor/16x16/apps/amor.png
debian/tmp/usr/share/icons/hicolor/22x22/apps/amor.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/amor.png
debian/tmp/usr/share/icons/hicolor/48x48/apps/amor.png
debian/tmp/usr/share/man/man1/amor.1

debian/icons/amor.xpm	usr/share/pixmaps
