debian/tmp/usr/bin/kodo
debian/tmp/usr/share/applications/tde/kodo.desktop
debian/tmp/usr/share/apps/kodo/numbers.png
debian/tmp/usr/share/doc/tde/HTML/en/kodo/*.bz2
debian/tmp/usr/share/doc/tde/HTML/en/kodo/*.docbook
debian/tmp/usr/share/doc/tde/HTML/en/kodo/*.png
debian/tmp/usr/share/doc/tde/HTML/en/kodo/common
debian/tmp/usr/share/icons/hicolor/16x16/apps/kodo.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/kodo.png
debian/tmp/usr/share/icons/hicolor/48x48/apps/kodo.png
debian/tmp/usr/share/man/man1/kodo.1

debian/icons/kodo.xpm	usr/share/pixmaps
