debian/tmp/usr/lib/*/trinity/kolourpicker_panelapplet.la
debian/tmp/usr/lib/*/trinity/kolourpicker_panelapplet.so
debian/tmp/usr/lib/*/trinity/ktimemon_panelapplet.la
debian/tmp/usr/lib/*/trinity/ktimemon_panelapplet.so
debian/tmp/usr/lib/*/trinity/math_panelapplet.la
debian/tmp/usr/lib/*/trinity/math_panelapplet.so
debian/tmp/usr/lib/*/trinity/mediacontrol_panelapplet.la
debian/tmp/usr/lib/*/trinity/mediacontrol_panelapplet.so
debian/tmp/usr/lib/*/trinity/kbinaryclock_panelapplet.la
debian/tmp/usr/lib/*/trinity/kbinaryclock_panelapplet.so
debian/tmp/usr/share/apps/kicker/applets
debian/tmp/usr/share/apps/mediacontrol
debian/tmp/usr/share/config.kcfg/kbinaryclock.kcfg
debian/tmp/usr/share/doc/tde/HTML/en/kicker-applets/common
debian/tmp/usr/share/doc/tde/HTML/en/kicker-applets/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/kicker-applets/*.docbook
debian/tmp/usr/share/icons/locolor/16x16/apps/ktimemon.png
debian/tmp/usr/share/icons/locolor/32x32/apps/ktimemon.png
debian/tmp/usr/share/icons/crystalsvg/16x16/apps/ktimemon.png
debian/tmp/usr/share/icons/crystalsvg/32x32/apps/ktimemon.png
kicker-applets/kolourpicker/TODO /usr/share/doc/kicker-applets/kolourpicker
kicker-applets/mediacontrol/AUTHORS /usr/share/doc/kicker-applets/mediacontrol
kicker-applets/mediacontrol/README /usr/share/doc/kicker-applets/mediacontrol
kicker-applets/mediacontrol/TODO /usr/share/doc/kicker-applets/mediacontrol
kicker-applets/ktimemon/README /usr/share/doc/kicker-applets/ktimemon
kicker-applets/ktimemon/TODO /usr/share/doc/kicker-applets/ktimemon
