debian/tmp/usr/bin/kcron
debian/tmp/usr/share/applications/tde/kcron.desktop
debian/tmp/usr/share/apps/kcron/kcronui.rc
debian/tmp/usr/share/doc/tde/HTML/en/kcron/common
debian/tmp/usr/share/doc/tde/HTML/en/kcron/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/kcron/index.docbook
debian/tmp/usr/share/doc/tde/HTML/en/kcron/kcron.png
debian/tmp/usr/share/doc/tde/HTML/en/kcron/kcronstart.png
debian/tmp/usr/share/doc/tde/HTML/en/kcron/newtask.png
debian/tmp/usr/share/doc/tde/HTML/en/kcron/newvariable.png
debian/tmp/usr/share/doc/tde/HTML/en/kcron/print.png
debian/tmp/usr/share/icons/hicolor/16x16/apps/kcron.png
debian/tmp/usr/share/icons/hicolor/22x22/apps/kcron.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/kcron.png

debian/icons/kcron.xpm		/usr/share/pixmaps
debian/icons/kcron-16.xpm	/usr/share/pixmaps
