debian/tmp/usr/bin/ksysv
debian/tmp/usr/share/applications/tde/ksysv.desktop
debian/tmp/usr/share/apps/ksysv/ksysvui.rc
debian/tmp/usr/share/apps/ksysv/pics/ksysv_locked.png
debian/tmp/usr/share/apps/ksysv/pics/ksysv_restart.png
debian/tmp/usr/share/apps/ksysv/pics/ksysv_start.png
debian/tmp/usr/share/apps/ksysv/pics/ksysv_stop.png
debian/tmp/usr/share/apps/ksysv/pics/ksysv_unlocked.png
debian/tmp/usr/share/doc/tde/HTML/en/ksysv/common
debian/tmp/usr/share/doc/tde/HTML/en/ksysv/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/ksysv/index.docbook
debian/tmp/usr/share/icons/hicolor/16x16/apps/ksysv.png
debian/tmp/usr/share/icons/hicolor/22x22/apps/ksysv.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/ksysv.png
debian/tmp/usr/share/icons/hicolor/48x48/apps/ksysv.png
debian/tmp/usr/share/mimelnk/application/x-ksysv.desktop
debian/tmp/usr/share/mimelnk/text/x-ksysv-log.desktop

debian/icons/ksysv.xpm		/usr/share/pixmaps
debian/icons/ksysv-16.xpm	/usr/share/pixmaps
