debian/tmp/usr/bin/kuser
debian/tmp/usr/share/applications/tde/kuser.desktop
debian/tmp/usr/share/apps/kuser/icons/crystalsvg/22x22/actions/add_group.png
debian/tmp/usr/share/apps/kuser/icons/crystalsvg/22x22/actions/add_user.png
debian/tmp/usr/share/apps/kuser/icons/crystalsvg/22x22/actions/delete_group.png
debian/tmp/usr/share/apps/kuser/icons/crystalsvg/22x22/actions/delete_user.png
debian/tmp/usr/share/apps/kuser/icons/crystalsvg/22x22/actions/edit_group.png
debian/tmp/usr/share/apps/kuser/icons/crystalsvg/22x22/actions/edit_user.png
debian/tmp/usr/share/apps/kuser/kuserui.rc
debian/tmp/usr/share/apps/kuser/pics/group.png
debian/tmp/usr/share/apps/kuser/pics/user.png
debian/tmp/usr/share/config.kcfg/kuser.kcfg
debian/tmp/usr/share/doc/tde/HTML/en/kuser/common
debian/tmp/usr/share/doc/tde/HTML/en/kuser/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/kuser/index.docbook
debian/tmp/usr/share/doc/tde/HTML/en/kuser/kuser.png
debian/tmp/usr/share/icons/hicolor/128x128/apps/kuser.png
debian/tmp/usr/share/icons/hicolor/16x16/apps/kuser.png
debian/tmp/usr/share/icons/hicolor/22x22/apps/kuser.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/kuser.png
debian/tmp/usr/share/icons/hicolor/48x48/apps/kuser.png
debian/tmp/usr/share/icons/hicolor/64x64/apps/kuser.png

debian/icons/kuser.xpm		/usr/share/pixmaps
debian/icons/kuser-16.xpm	/usr/share/pixmaps
