usr/bin/blinken
/usr/share/applications/tde/blinken.desktop
/usr/share/apps/blinken/images
/usr/share/apps/blinken/sounds
/usr/share/config.kcfg/blinken.kcfg
/usr/share/doc/tde/HTML/en/blinken
/usr/share/icons/hicolor/16x16/apps/blinken.png
/usr/share/icons/hicolor/22x22/apps/blinken.png
/usr/share/icons/hicolor/32x32/apps/blinken.png
/usr/share/icons/hicolor/48x48/apps/blinken.png
/usr/share/icons/hicolor/64x64/apps/blinken.png
/usr/share/icons/hicolor/128x128/apps/blinken.png
/usr/share/icons/hicolor/scalable/apps/blinken.svgz
/usr/share/man/man1/blinken.1
../icons/blinken.xpm /usr/share/pixmaps
