usr/bin/kiten
usr/bin/kitengen
/usr/share/applications/tde/kiten.desktop
/usr/share/doc/tde/HTML/en/kiten/common
/usr/share/doc/tde/HTML/en/kiten/index.cache.bz2
/usr/share/doc/tde/HTML/en/kiten/*.docbook
/usr/share/doc/tde/HTML/en/kiten/*.png
/usr/share/icons/hicolor/16x16/apps/kiten.png
/usr/share/icons/hicolor/32x32/apps/kiten.png
/usr/share/icons/hicolor/48x48/apps/kiten.png
/usr/share/icons/hicolor/128x128/apps/kiten.png
/usr/share/icons/hicolor/scalable/apps/kiten.svgz
/usr/share/man/man1/kiten.1
/usr/share/man/man1/kitengen.1
../icons/kiten.xpm /usr/share/pixmaps
