etc/trinity/kstarsrc
usr/bin/kstars
/usr/include/kstarsinterface.h
/usr/include/simclockinterface.h
/usr/share/applications/tde/kstars.desktop
/usr/share/config.kcfg/kstars.kcfg
/usr/share/doc/tde/HTML/en/kstars/common
/usr/share/doc/tde/HTML/en/kstars/index.cache.bz2
/usr/share/doc/tde/HTML/en/kstars/*.docbook
/usr/share/doc/tde/HTML/en/kstars/*.png
/usr/share/icons/hicolor/16x16/apps/kstars.png
/usr/share/icons/hicolor/32x32/apps/kstars.png
/usr/share/icons/hicolor/48x48/apps/kstars.png
/usr/share/icons/hicolor/64x64/apps/kstars.png
/usr/share/icons/hicolor/128x128/apps/kstars.png
/usr/share/icons/hicolor/scalable/apps/kstars.svgz
/usr/share/man/man1/kstars.1
../icons/kstars.xpm /usr/share/pixmaps
