usr/bin/ktouch
/usr/share/applications/tde/ktouch.desktop
/usr/share/apps/ktouch
/usr/share/config.kcfg/ktouch.kcfg
/usr/share/doc/tde/HTML/en/ktouch/common
/usr/share/doc/tde/HTML/en/ktouch/index.cache.bz2
/usr/share/doc/tde/HTML/en/ktouch/*.docbook
/usr/share/doc/tde/HTML/en/ktouch/*.png
/usr/share/icons/hicolor/16x16/apps/ktouch.png
/usr/share/icons/hicolor/22x22/apps/ktouch.png
/usr/share/icons/hicolor/32x32/apps/ktouch.png
/usr/share/icons/hicolor/48x48/apps/ktouch.png
/usr/share/icons/hicolor/128x128/apps/ktouch.png
/usr/share/icons/hicolor/scalable/apps/ktouch.svgz
/usr/share/man/man1/ktouch.1
../icons/ktouch.xpm /usr/share/pixmaps
