debian/tmp/usr/share/doc/tde/HTML/en/tdevelop
debian/tmp/usr/share/doc/tde/HTML/en/tdevelop-apidocs
debian/tmp/usr/share/doc/tde/HTML/en/tde_app_devel/appwizard.png
debian/tmp/usr/share/doc/tde/HTML/en/tde_app_devel/index.docbook
debian/tmp/usr/share/doc/tde/HTML/en/tde_app_devel/kscribblefiles.png
debian/tmp/usr/share/doc/tde/HTML/en/tde_app_devel/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/tde_app_devel/common
