/usr/bin/akregator
/usr/lib/*/trinity/libakregatorpart.la
/usr/lib/*/trinity/libakregatorpart.so
/usr/lib/*/trinity/libakregator_mk4storage_plugin.la
/usr/lib/*/trinity/libakregator_mk4storage_plugin.so
/usr/lib/*/libakregatorprivate.la
/usr/lib/*/libakregatorprivate.so
/usr/lib/*/libakregatorprivate.so.0
/usr/lib/*/libakregatorprivate.so.0.0.0
/usr/share/applications/tde/akregator.desktop
/usr/share/apps/akregator
/usr/share/config.kcfg/akregator.kcfg
/usr/share/config.kcfg/mk4config.kcfg
/usr/share/doc/tde/HTML/en/akregator
/usr/share/doc/tde/HTML/en/tdeioslave/feed
/usr/share/icons/hicolor/128x128/apps/akregator.png
/usr/share/icons/crystalsvg/16x16/actions/rss_tag.png
/usr/share/icons/crystalsvg/22x22/actions/rss_tag.png
/usr/share/icons/crystalsvg/32x32/actions/rss_tag.png
/usr/share/icons/crystalsvg/48x48/actions/rss_tag.png
/usr/share/icons/crystalsvg/64x64/actions/rss_tag.png
/usr/share/icons/crystalsvg/16x16/apps/akregator_empty.png
/usr/share/icons/hicolor/16x16/apps/akregator.png
/usr/share/icons/hicolor/22x22/apps/akregator.png
/usr/share/icons/hicolor/32x32/apps/akregator.png
/usr/share/icons/hicolor/48x48/apps/akregator.png
/usr/share/icons/hicolor/64x64/apps/akregator.png
/usr/share/icons/hicolor/scalable/apps/akregator.svgz
/usr/share/services/akregator_mk4storage_plugin.desktop
/usr/share/services/akregator_part.desktop
/usr/share/services/feed.protocol
/usr/share/services/kontact/akregatorplugin*.desktop
/usr/share/servicetypes/akregator_plugin.desktop
../icons/akregator.xpm /usr/share/pixmaps
../icons/akregator-16.xpm /usr/share/pixmaps

