/usr/bin/kalarm
/usr/bin/kalarmd
/usr/share/applications/tde/kalarm.desktop
/usr/share/applnk/.hidden/kalarmd.desktop
/usr/share/applnk/Applications/kalarm.desktop
/usr/share/apps/kalarm
/usr/share/autostart/kalarm.tray.desktop
/usr/share/autostart/kalarmd.autostart.desktop
/usr/share/doc/tde/HTML/en/kalarm
/usr/share/icons/crystalsvg/16x16/actions/kalarm.png
/usr/share/icons/hicolor/16x16/apps/kalarm.png
/usr/share/icons/crystalsvg/22x22/actions/kalarm.png
/usr/share/icons/hicolor/32x32/apps/kalarm.png
/usr/share/icons/hicolor/48x48/apps/kalarm.png
../icons/kalarm.xpm /usr/share/pixmaps
../icons/kalarm-16.xpm /usr/share/pixmaps
