/usr/bin/karm
/usr/lib/*/libkarm.so
/usr/lib/*/libkarm.so.0
/usr/lib/*/libkarm.so.0.0.0
/usr/lib/*/trinity/libkarmpart.la
/usr/lib/*/trinity/libkarmpart.so
/usr/share/applications/tde/karm.desktop
/usr/share/applnk/Utilities/karm.desktop
/usr/share/apps/karm
/usr/share/apps/karmpart
/usr/share/doc/tde/HTML/en/karm
/usr/share/icons/hicolor/128x128/apps/karm.png
/usr/share/icons/hicolor/16x16/apps/karm.png
/usr/share/icons/hicolor/22x22/apps/karm.png
/usr/share/icons/hicolor/32x32/apps/karm.png
/usr/share/icons/hicolor/48x48/apps/karm.png
/usr/share/icons/hicolor/64x64/apps/karm.png
/usr/share/services/karm_part.desktop
/usr/share/services/kontact/karmplugin.desktop
../icons/karm.xpm /usr/share/pixmaps
../icons/karm-16.xpm /usr/share/pixmaps
