/usr/bin/knode
/usr/lib/*/trinity/kcm_knode.la
/usr/lib/*/trinity/kcm_knode.so
/usr/lib/*/trinity/libknodepart.la
/usr/lib/*/trinity/libknodepart.so
/usr/lib/*/libknodecommon.la
/usr/lib/*/libknodecommon.so
/usr/lib/*/libknodecommon.so.3
/usr/lib/*/libknodecommon.so.3.0.0
/usr/share/applications/tde/KNode.desktop
/usr/share/apps/knode
/usr/share/doc/tde/HTML/en/knode
/usr/share/icons/hicolor/128x128/apps/knode.png
/usr/share/icons/hicolor/128x128/apps/knode2.png
/usr/share/icons/hicolor/16x16/apps/knode.png
/usr/share/icons/hicolor/16x16/apps/knode2.png
/usr/share/icons/hicolor/32x32/apps/knode.png
/usr/share/icons/hicolor/32x32/apps/knode2.png
/usr/share/icons/hicolor/48x48/apps/knode.png
/usr/share/icons/hicolor/48x48/apps/knode2.png
/usr/share/icons/hicolor/64x64/apps/knode.png
/usr/share/icons/hicolor/64x64/apps/knode2.png
/usr/share/services/knewsservice.protocol
/usr/share/services/knode_config_*.desktop
/usr/share/services/kontact/knodeplugin.desktop
../icons/knode.xpm /usr/share/pixmaps
../icons/knode-16.xpm /usr/share/pixmaps
