/usr/bin/konsolekalendar
/usr/share/applications/tde/konsolekalendar.desktop
/usr/share/doc/tde/HTML/en/konsolekalendar/common
/usr/share/doc/tde/HTML/en/konsolekalendar/index.cache.bz2
/usr/share/doc/tde/HTML/en/konsolekalendar/index.docbook
/usr/share/icons/crystalsvg/16x16/apps/konsolekalendar.png
/usr/share/icons/crystalsvg/22x22/apps/konsolekalendar.png
/usr/share/icons/crystalsvg/32x32/apps/konsolekalendar.png
