/usr/bin/korn
/usr/lib/*/tdeconf_update_bin/korn-3-4-config_change
/usr/share/applications/tde/KOrn.desktop
/usr/share/apps/tdeconf_update/korn-3-4-config_change.upd
/usr/share/apps/tdeconf_update/korn-3-5-metadata-update.pl
/usr/share/apps/tdeconf_update/korn-3-5-ssl-update.pl
/usr/share/apps/tdeconf_update/korn-3-5-update.upd
/usr/share/doc/tde/HTML/en/korn
/usr/share/icons/hicolor/16x16/apps/korn.png
/usr/share/icons/hicolor/32x32/apps/korn.png
/usr/share/icons/hicolor/48x48/apps/korn.png
../icons/korn.xpm /usr/share/pixmaps
../icons/korn-16.xpm /usr/share/pixmaps
