debian/tmp/opt/trinity/include/tde/kjsembed/*
debian/tmp/opt/trinity/lib/libkjsembed.so
debian/tmp/opt/trinity/lib/libkjsembed.la

kjsembed/plugins/customobject_plugin.cpp		/opt/trinity/share/doc/libkjsembed-trinity-dev/plugin-examples/customobject/
kjsembed/plugins/customobject_plugin.h			/opt/trinity/share/doc/libkjsembed-trinity-dev/plugin-examples/customobject/
kjsembed/plugins/customobject_plugin.desktop		/opt/trinity/share/doc/libkjsembed-trinity-dev/plugin-examples/customobject/
kjsembed/plugins/customqobject_plugin.cpp		/opt/trinity/share/doc/libkjsembed-trinity-dev/plugin-examples/customqobject/
kjsembed/plugins/customqobject_plugin.h			/opt/trinity/share/doc/libkjsembed-trinity-dev/plugin-examples/customqobject/
kjsembed/plugins/customqobject_plugin.desktop		/opt/trinity/share/doc/libkjsembed-trinity-dev/plugin-examples/customqobject/

kjsembed/docs/embedding/simple-embed/demo.html             /opt/trinity/share/doc/libkjsembed-trinity-dev/embedding-examples/simple-embed/
kjsembed/docs/embedding/simple-embed/embedjs.desktop       /opt/trinity/share/doc/libkjsembed-trinity-dev/embedding-examples/simple-embed/
kjsembed/docs/embedding/simple-embed/embedjsui.rc          /opt/trinity/share/doc/libkjsembed-trinity-dev/embedding-examples/simple-embed/
kjsembed/docs/embedding/simple-embed/embedviewimp.cpp      /opt/trinity/share/doc/libkjsembed-trinity-dev/embedding-examples/simple-embed/
kjsembed/docs/embedding/simple-embed/embedviewimp.h        /opt/trinity/share/doc/libkjsembed-trinity-dev/embedding-examples/simple-embed/
kjsembed/docs/embedding/simple-embed/embedview.ui          /opt/trinity/share/doc/libkjsembed-trinity-dev/embedding-examples/simple-embed/
kjsembed/docs/embedding/simple-embed/hi16-app-embedjs.png  /opt/trinity/share/doc/libkjsembed-trinity-dev/embedding-examples/simple-embed/
kjsembed/docs/embedding/simple-embed/hi32-app-embedjs.png  /opt/trinity/share/doc/libkjsembed-trinity-dev/embedding-examples/simple-embed/
kjsembed/docs/embedding/simple-embed/main.cpp              /opt/trinity/share/doc/libkjsembed-trinity-dev/embedding-examples/simple-embed/
kjsembed/docs/embedding/simple-embed/Makefile.am           /opt/trinity/share/doc/libkjsembed-trinity-dev/embedding-examples/simple-embed/
kjsembed/docs/embedding/simple-embed/README                /opt/trinity/share/doc/libkjsembed-trinity-dev/embedding-examples/simple-embed/
kjsembed/docs/embedding/simple-embed/test.js               /opt/trinity/share/doc/libkjsembed-trinity-dev/embedding-examples/simple-embed/

