debian/tmp/opt/trinity/lib/libtqtjavasupport.la
debian/tmp/opt/trinity/lib/libtqtjavasupport.so
debian/tmp/opt/trinity/lib/libtqtjavasupport.so.1
debian/tmp/opt/trinity/lib/libtqtjavasupport.so.1.0.0

debian/tmp/opt/trinity/lib/jni/libtqtjava.la
debian/tmp/opt/trinity/lib/jni/libtqtjava.so
debian/tmp/opt/trinity/lib/jni/libtqtjava.so.1
debian/tmp/opt/trinity/lib/jni/libtqtjava.so.1.0.0

qtjava/ChangeLog /opt/trinity/share/doc/libqt3-jni
