#! /bin/sh -e

case "$1" in

    configure)
        [ -d /root/.trinity/share/config ] ||
        mkdir -p /root/.trinity/share/config

        if [ ! -f /root/.trinity/share/config/kdeglobals ]; then
            RELEASE_VERSION="$(/opt/trinity/bin/tde-config --version | sed -n 's|^TDE: ||p')"
            /opt/trinity/bin/kwriteconfig --file /root/.trinity/share/config/kdeglobals \
                --group "Release Notes" \
                --key "$RELEASE_VERSION" \
                --type bool "true"
        fi
        if [ ! -f /root/.trinity/share/config/kpersonalizerrc ]; then
            /opt/trinity/bin/kwriteconfig --file /root/.trinity/share/config/kpersonalizerrc \
                --group "General" \
                --key "FirstLogin" \
                --type bool "false"
        fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac

#DEBHELPER#

exit 0
