debian/tmp/usr/bin/kdvi
debian/tmp/usr/lib/*/trinity/kdvipart.la
debian/tmp/usr/lib/*/trinity/kdvipart.so
debian/tmp/usr/share/applications/tde/kdvi.desktop
debian/tmp/usr/share/apps/kdvi/kdvi_part.rc
debian/tmp/usr/share/apps/kdvi/kviewshell.rc
debian/tmp/usr/share/apps/kdvi/tips
debian/tmp/usr/share/config.kcfg/kdvi.kcfg
debian/tmp/usr/share/doc/tde/HTML/en/kdvi/aboutkde.ps
debian/tmp/usr/share/doc/tde/HTML/en/kdvi/common
debian/tmp/usr/share/doc/tde/HTML/en/kdvi/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/kdvi/index.docbook
debian/tmp/usr/share/doc/tde/HTML/en/kdvi/KDVI-features.dvi
debian/tmp/usr/share/doc/tde/HTML/en/kdvi/KDVI-features.tex
debian/tmp/usr/share/doc/tde/HTML/en/kdvi/kdvi-search.el
debian/tmp/usr/share/doc/tde/HTML/en/kdvi/optionrequester1.png
debian/tmp/usr/share/doc/tde/HTML/en/kdvi/optionrequester2.png
debian/tmp/usr/share/doc/tde/HTML/en/kdvi/srcltx.sty
debian/tmp/usr/share/doc/tde/HTML/en/kdvi/srctex.sty
debian/tmp/usr/share/icons/hicolor/16x16/apps/kdvi.png
debian/tmp/usr/share/icons/hicolor/22x22/apps/kdvi.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/kdvi.png
debian/tmp/usr/share/icons/hicolor/48x48/apps/kdvi.png
debian/tmp/usr/share/icons/hicolor/scalable/apps/kdvi.svgz
debian/tmp/usr/share/man/man1/kdvi.1
debian/tmp/usr/share/services/kdvimultipage.desktop

debian/icons/kdvi.xpm		/usr/share/pixmaps
debian/icons/kdvi-16.xpm	/usr/share/pixmaps
