debian/tmp/usr/bin/kfaxview
debian/tmp/usr/lib/*/trinity/kfaxviewpart.so
debian/tmp/usr/lib/*/trinity/kfaxviewpart.la
debian/tmp/usr/lib/*/libkfaximage.so
debian/tmp/usr/lib/*/libkfaximage.la
debian/tmp/usr/share/applications/tde/kfaxview.desktop
debian/tmp/usr/share/apps/kfaxview/kviewshell.rc
debian/tmp/usr/share/icons/hicolor/16x16/apps/kfaxview.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/kfaxview.png
debian/tmp/usr/share/icons/hicolor/22x22/apps/kfaxview.png
debian/tmp/usr/share/icons/hicolor/48x48/apps/kfaxview.png
debian/tmp/usr/share/icons/hicolor/scalable/apps/kfaxview.svgz
debian/tmp/usr/share/man/man1/kfaxview.1
debian/tmp/usr/share/services/kfaxmultipage.desktop
debian/tmp/usr/share/services/kfaxmultipage_tiff.desktop

debian/icons/kfaxview.xpm           /usr/share/pixmaps
debian/icons/kfaxview-16.xpm        /usr/share/pixmaps
