debian/tmp/usr/bin/kfax
debian/tmp/usr/share/applications/tde/kfax.desktop
debian/tmp/usr/share/apps/kfax/kfaxui.rc
debian/tmp/usr/share/apps/kfax/pics/kfax.tif
debian/tmp/usr/share/apps/kfax/pics/kfaxlogo.xpm
debian/tmp/usr/share/icons/hicolor/16x16/apps/kfax.png
debian/tmp/usr/share/icons/hicolor/22x22/apps/kfax.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/kfax.png
debian/tmp/usr/share/icons/hicolor/48x48/apps/kfax.png
debian/tmp/usr/share/icons/hicolor/scalable/apps/kfax.svgz
debian/tmp/usr/share/man/man1/kfax.1

debian/icons/kfax.xpm		/usr/share/pixmaps
debian/icons/kfax-16.xpm	/usr/share/pixmaps
