debian/tmp/usr/bin/kuickshow
debian/tmp/usr/lib/*/trinity/kuickshow.la
debian/tmp/usr/lib/*/trinity/kuickshow.so
debian/tmp/usr/lib/*/libtdeinit_kuickshow.so
debian/tmp/usr/share/applications/tde/kuickshow.desktop
debian/tmp/usr/share/apps/kuickshow/im_palette.pal
debian/tmp/usr/share/apps/kuickshow/pics/about.png
debian/tmp/usr/share/apps/kuickshow/pics/calibrate.png
debian/tmp/usr/share/apps/kuickshow/pics/handcursor.png
debian/tmp/usr/share/apps/kuickshow/pics/imageviewer-medium.png
debian/tmp/usr/share/apps/kuickshow/pics/imageviewer-small.png
debian/tmp/usr/share/apps/kuickshow/pics/ksslide.png
debian/tmp/usr/share/apps/kuickshow/pics/kuickshow-day.jpg
debian/tmp/usr/share/apps/kuickshow/pics/kuickshow-night.jpg
debian/tmp/usr/share/apps/kuickshow/pics/logo.png
debian/tmp/usr/share/doc/tde/HTML/en/kuickshow/common
debian/tmp/usr/share/doc/tde/HTML/en/kuickshow/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/kuickshow/index.docbook
debian/tmp/usr/share/doc/tde/HTML/en/kuickshow/screenshot.png
debian/tmp/usr/share/icons/hicolor/16x16/apps/kuickshow.png
debian/tmp/usr/share/icons/hicolor/22x22/apps/kuickshow.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/kuickshow.png
debian/tmp/usr/share/man/man1/kuickshow.1

debian/icons/kuickshow.xpm		/usr/share/pixmaps
debian/icons/kuickshow-16.xpm		/usr/share/pixmaps

debian/tmp/usr/share/doc/tde/HTML/en/kuickshow/screenshot.png
debian/tmp/usr/share/doc/tde/HTML/en/kuickshow/common
debian/tmp/usr/share/doc/tde/HTML/en/kuickshow/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/kuickshow/index.docbook
