debian/tmp/opt/trinity/bin/rosegarden*
debian/tmp/opt/trinity/bin/rosegardensequencer*
debian/tmp/opt/trinity/share/applications
debian/tmp/opt/trinity/share/mimelnk
debian/tmp/opt/trinity/share/man/man1/rosegarden.1
debian/tmp/opt/trinity/share/man/man1/rosegarden-lilypondview.1
debian/tmp/opt/trinity/share/man/man1/rosegarden-project-package.1
debian/tmp/opt/trinity/share/man/man1/rosegarden-audiofile-importer.1
