debian/tmp/opt/trinity/bin/kmix
debian/tmp/opt/trinity/bin/kmixctrl
debian/tmp/opt/trinity/lib/trinity/kmix.la
debian/tmp/opt/trinity/lib/trinity/kmix.so
debian/tmp/opt/trinity/lib/trinity/kmix_panelapplet.la
debian/tmp/opt/trinity/lib/trinity/kmix_panelapplet.so
debian/tmp/opt/trinity/lib/trinity/kmixctrl.la
debian/tmp/opt/trinity/lib/trinity/kmixctrl.so
debian/tmp/opt/trinity/lib/libtdeinit_kmix.so
debian/tmp/opt/trinity/lib/libtdeinit_kmixctrl.so
debian/tmp/opt/trinity/share/applications/tde/kmix.desktop
debian/tmp/opt/trinity/share/apps/kicker/applets/kmixapplet.desktop
debian/tmp/opt/trinity/share/apps/kmix/kmixui.rc
debian/tmp/opt/trinity/share/apps/kmix/pics/Listener.png
debian/tmp/opt/trinity/share/apps/kmix/pics/Speaker*.png
debian/tmp/opt/trinity/share/apps/kmix/pics/mix*.png
debian/tmp/opt/trinity/share/apps/kmix/pics/crystal/*.png
debian/tmp/opt/trinity/share/apps/kmix/pics/oldcrystal/*.png
debian/tmp/opt/trinity/share/autostart/restore_kmix_volumes.desktop
debian/tmp/opt/trinity/share/autostart/kmix.desktop
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kmix/common
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kmix/index.cache.bz2
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kmix/index.docbook
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kmix/kmix-channel-playback.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kmix/kmix-channel-record.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kmix/kmix-window.png
debian/tmp/opt/trinity/share/icons/hicolor/128x128/apps/kmix.png
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/kmix.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/kmix.png
debian/tmp/opt/trinity/share/icons/hicolor/48x48/apps/kmix.png
debian/tmp/opt/trinity/share/icons/hicolor/64x64/apps/kmix.png
debian/tmp/opt/trinity/share/man/man1/kmix.1
debian/tmp/opt/trinity/share/man/man1/kmixctrl.1
debian/tmp/opt/trinity/share/services/kmixctrl_restore.desktop

debian/icons/kmix.xpm		/opt/trinity/share/pixmaps
debian/icons/kmix-16.xpm	/opt/trinity/share/pixmaps

debian/tmp/opt/trinity/share/doc/tde/HTML/en/kmix/kmix-channel-switches.png
