debian/tmp/usr/lib/*/libkjsembed.so.1.0.0
debian/tmp/usr/lib/*/libkjsembed.so.1

debian/tmp/usr/lib/*/trinity/libimagefxplugin.la
debian/tmp/usr/lib/*/trinity/libimagefxplugin.so
debian/tmp/usr/share/services/imagefx_plugin.desktop

debian/tmp/usr/lib/*/trinity/libqprocessplugin.so
debian/tmp/usr/lib/*/trinity/libqprocessplugin.la
debian/tmp/usr/share/services/qprocess_plugin.desktop

debian/tmp/usr/lib/*/trinity/libfileitemplugin.la
debian/tmp/usr/lib/*/trinity/libfileitemplugin.so
debian/tmp/usr/share/services/tdefileitem_plugin.desktop

debian/tmp/usr/share/apps/kjsembed/cmdline.js
debian/tmp/usr/share/servicetypes/binding_type.desktop

debian/tmp/usr/bin/embedjs
debian/tmp/usr/share/apps/embedjs/embedjsui.rc
debian/tmp/usr/share/applnk/Utilities/embedjs.desktop
debian/tmp/usr/share/icons/hicolor/16x16/apps/embedjs.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/embedjs.png

debian/tmp/usr/lib/*/trinity/libjavascript.la
debian/tmp/usr/lib/*/trinity/libjavascript.so
debian/tmp/usr/share/apps/kate/scripts/swaptabs.js
debian/tmp/usr/share/apps/kate/scripts/swaptabs.ui
debian/tmp/usr/share/apps/kate/scripts/swaptabs.desktop
debian/tmp/usr/share/services/javascript.desktop

kjsembed/docs/ChangeLog /usr/share/doc/libkjsembed1
