debian/tmp/usr/bin/rbtdesh
debian/tmp/usr/bin/rbtdeapi
debian/tmp/usr/bin/krubyinit
debian/tmp/usr/bin/rbtdeconfig_compiler

debian/tmp/usr/lib/ruby/*/Korundum.rb
debian/tmp/usr/lib/ruby/*/TDE/korundum.rb

debian/tmp/usr/lib/*/*/*/korundum.so*
debian/tmp/usr/lib/*/*/*/korundum.la

debian/tmp/usr/share/man/man1/krubyinit.1
debian/tmp/usr/share/man/man1/rbtdesh.1
debian/tmp/usr/share/man/man1/rbtdeapi.1

korundum/ChangeLog /usr/share/doc/libkorundum0-ruby
