/usr/games/kasteroids
/usr/share/icons/hicolor/128x128/apps/kasteroids.png
/usr/share/icons/hicolor/64x64/apps/kasteroids.png
/usr/share/icons/hicolor/48x48/apps/kasteroids.png
/usr/share/icons/hicolor/32x32/apps/kasteroids.png
/usr/share/icons/hicolor/22x22/apps/kasteroids.png
/usr/share/icons/hicolor/16x16/apps/kasteroids.png
/usr/share/applications/tde/kasteroids.desktop
/usr/share/apps/kasteroids/*
/usr/share/config.kcfg/kasteroids.kcfg
/usr/share/doc/tde/HTML/en/kasteroids/*
/usr/share/man/man6/kasteroids.6
../icons/kasteroids.xpm /usr/share/pixmaps
../icons/kasteroids-16.xpm /usr/share/pixmaps
