/usr/share/apps/kblackbox/*
/usr/share/icons/hicolor/128x128/apps/kblackbox.png
/usr/share/icons/hicolor/64x64/apps/kblackbox.png
/usr/share/icons/hicolor/48x48/apps/kblackbox.png
/usr/share/icons/hicolor/32x32/apps/kblackbox.png
/usr/share/icons/hicolor/22x22/apps/kblackbox.png
/usr/share/icons/hicolor/16x16/apps/kblackbox.png
/usr/share/applications/tde/kblackbox.desktop
/usr/games/kblackbox
/usr/share/doc/tde/HTML/en/kblackbox/*
/usr/share/man/man6/kblackbox.6
../icons/kblackbox.xpm /usr/share/pixmaps
../icons/kblackbox-16.xpm /usr/share/pixmaps
