/usr/share/apps/kenolaba/*
/usr/share/icons/hicolor/16x16/apps/kenolaba.png
/usr/share/icons/hicolor/22x22/apps/kenolaba.png
/usr/share/icons/hicolor/32x32/apps/kenolaba.png
/usr/share/icons/hicolor/48x48/apps/kenolaba.png
/usr/share/icons/hicolor/64x64/apps/kenolaba.png
/usr/share/icons/hicolor/128x128/apps/kenolaba.png
/usr/share/applications/tde/kenolaba.desktop
/usr/games/kenolaba
/usr/share/doc/tde/HTML/en/kenolaba/*
/usr/share/man/man6/kenolaba.6
../icons/kenolaba.xpm /usr/share/pixmaps
../icons/kenolaba-16.xpm /usr/share/pixmaps
