/usr/games/knetwalk
/usr/share/applications/tde/knetwalk.desktop
/usr/share/apps/knetwalk
/usr/share/icons/hicolor/22x22/apps/knetwalk.png
/usr/share/icons/hicolor/32x32/apps/knetwalk.png
/usr/share/icons/hicolor/64x64/apps/knetwalk.png
/usr/share/icons/hicolor/128x128/apps/knetwalk.png
/usr/share/man/man6/knetwalk.6
../icons/knetwalk.xpm /usr/share/pixmaps
../icons/knetwalk-16.xpm /usr/share/pixmaps
