/etc/trinity/magic/kolf.magic
/etc/trinity/magic/kolf.magic.mgc
/usr/share/apps/kolf/*
/usr/games/kolf
/usr/share/applications/tde/kolf.desktop
/usr/share/doc/tde/HTML/en/kolf/*
/usr/share/icons/hicolor/16x16/apps/kolf.png
/usr/share/icons/hicolor/22x22/apps/kolf.png
/usr/share/icons/hicolor/32x32/apps/kolf.png
/usr/share/icons/hicolor/48x48/apps/kolf.png
/usr/share/icons/hicolor/64x64/apps/kolf.png
/usr/share/icons/hicolor/128x128/apps/kolf.png
/usr/share/mimelnk/application/x-kolf.desktop
/usr/share/mimelnk/application/x-kourse.desktop
/usr/lib/*/libtdeinit_kolf.so
/usr/lib/*/libtdeinit_kolf.la
/usr/lib/*/trinity/kolf.la
/usr/lib/*/trinity/kolf.so
/usr/lib/*/libkolf.la
/usr/lib/*/libkolf.so.1
/usr/lib/*/libkolf.so.1.2.0
/usr/share/man/man6/kolf.6
../icons/kolf.xpm /usr/share/pixmaps
../icons/kolf-16.xpm /usr/share/pixmaps
