/usr/share/apps/ksmiletris/*
/usr/share/icons/hicolor/128x128/apps/ksmiletris.png
/usr/share/icons/hicolor/64x64/apps/ksmiletris.png
/usr/share/icons/hicolor/48x48/apps/ksmiletris.png
/usr/share/icons/hicolor/32x32/apps/ksmiletris.png
/usr/share/icons/hicolor/22x22/apps/ksmiletris.png
/usr/share/icons/hicolor/16x16/apps/ksmiletris.png
/usr/share/applications/tde/ksmiletris.desktop
/usr/games/ksmiletris
/usr/share/doc/tde/HTML/en/ksmiletris/*
/usr/share/man/man6/ksmiletris.6
../icons/ksmiletris.xpm /usr/share/pixmaps
../icons/ksmiletris-16.xpm /usr/share/pixmaps
