/usr/share/applications/tde/ksokoban.desktop
/usr/share/icons/hicolor/128x128/apps/ksokoban.png
/usr/share/icons/hicolor/64x64/apps/ksokoban.png
/usr/share/icons/hicolor/48x48/apps/ksokoban.png
/usr/share/icons/hicolor/32x32/apps/ksokoban.png
/usr/share/icons/hicolor/22x22/apps/ksokoban.png
/usr/share/icons/hicolor/16x16/apps/ksokoban.png
/usr/games/ksokoban
/usr/share/doc/tde/HTML/en/ksokoban/*
/usr/share/man/man6/ksokoban.6
../icons/ksokoban.xpm /usr/share/pixmaps
../icons/ksokoban-16.xpm /usr/share/pixmaps
