/usr/games/ktron
/usr/share/icons/hicolor/16x16/apps/ktron.png
/usr/share/icons/hicolor/22x22/apps/ktron.png
/usr/share/icons/hicolor/32x32/apps/ktron.png
/usr/share/icons/hicolor/48x48/apps/ktron.png
/usr/share/icons/hicolor/64x64/apps/ktron.png
/usr/share/icons/hicolor/128x128/apps/ktron.png
/usr/share/doc/tde/HTML/en/ktron/*
/usr/share/applications/tde/ktron.desktop
/usr/share/apps/ktron/*
/usr/share/config.kcfg/ktron.kcfg
/usr/share/man/man6/ktron.6
../icons/ktron.xpm /usr/share/pixmaps
../icons/ktron-16.xpm /usr/share/pixmaps
