/usr/games/ktuberling
/usr/share/icons/hicolor/128x128/apps/ktuberling.png
/usr/share/icons/hicolor/64x64/apps/ktuberling.png
/usr/share/icons/hicolor/48x48/apps/ktuberling.png
/usr/share/icons/hicolor/32x32/apps/ktuberling.png
/usr/share/icons/hicolor/22x22/apps/ktuberling.png
/usr/share/icons/hicolor/16x16/apps/ktuberling.png
/usr/share/doc/tde/HTML/en/ktuberling/*
/usr/share/applications/tde/ktuberling.desktop
/usr/share/apps/ktuberling/*
/usr/share/mimelnk/application/x-tuberling.desktop
/usr/share/man/man6/ktuberling.6
../icons/ktuberling.xpm /usr/share/pixmaps
../icons/ktuberling-16.xpm /usr/share/pixmaps
