debian/tmp/usr/bin/ksayit
debian/tmp/usr/include/ksayit_fxplugin.h
debian/tmp/usr/lib/*/trinity/libFreeverb_plugin.la
debian/tmp/usr/lib/*/trinity/libFreeverb_plugin.so
debian/tmp/usr/lib/*/libKTTSD_Lib.la
debian/tmp/usr/lib/*/libKTTSD_Lib.so
debian/tmp/usr/lib/*/libKTTSD_Lib.so.0
debian/tmp/usr/lib/*/libKTTSD_Lib.so.0.0.1
debian/tmp/usr/share/applications/tde/ksayit.desktop
debian/tmp/usr/share/apps/ksayit/ContextMenus.xml
debian/tmp/usr/share/apps/ksayit/ksayitui.rc
debian/tmp/usr/share/icons/hicolor/16x16/apps/ksayit.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/ksayit.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/ksayit_clipempty.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/ksayit_talking.png
debian/tmp/usr/share/services/ksayit_libFreeverb.desktop
debian/tmp/usr/share/servicetypes/ksayit_libFreeverb_service.desktop
debian/tmp/usr/share/man/man1/ksayit.1

debian/icons/ksayit.xpm		/usr/share/pixmaps
debian/icons/ksayit-16.xpm	/usr/share/pixmaps
