debian/tmp/usr/bin/ark
debian/tmp/usr/lib/*/trinity/ark.la
debian/tmp/usr/lib/*/trinity/ark.so
debian/tmp/usr/lib/*/trinity/libarkpart.la
debian/tmp/usr/lib/*/trinity/libarkpart.so
debian/tmp/usr/lib/*/libtdeinit_ark.so
debian/tmp/usr/share/applications/tde/ark.desktop
debian/tmp/usr/share/apps/ark/ark_part.rc
debian/tmp/usr/share/apps/ark/ark_part_readonly.rc
debian/tmp/usr/share/apps/ark/arkui.rc
debian/tmp/usr/share/apps/ark/icons/crystalsvg/22x22/actions/ark_adddir.png
debian/tmp/usr/share/apps/ark/icons/crystalsvg/22x22/actions/ark_addfile.png
debian/tmp/usr/share/apps/ark/icons/crystalsvg/22x22/actions/ark_delete.png
debian/tmp/usr/share/apps/ark/icons/crystalsvg/22x22/actions/ark_extract.png
debian/tmp/usr/share/apps/ark/icons/crystalsvg/22x22/actions/ark_selectall.png
debian/tmp/usr/share/apps/ark/icons/crystalsvg/22x22/actions/ark_view.png
debian/tmp/usr/share/apps/ark/icons/crystalsvg/32x32/actions/ark_adddir.png
debian/tmp/usr/share/apps/ark/icons/crystalsvg/32x32/actions/ark_addfile.png
debian/tmp/usr/share/apps/ark/icons/crystalsvg/32x32/actions/ark_delete.png
debian/tmp/usr/share/apps/ark/icons/crystalsvg/32x32/actions/ark_extract.png
debian/tmp/usr/share/apps/ark/icons/crystalsvg/32x32/actions/ark_view.png
debian/tmp/usr/share/config.kcfg/ark.kcfg
debian/tmp/usr/share/doc/tde/HTML/en/ark/common
debian/tmp/usr/share/doc/tde/HTML/en/ark/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/ark/index.docbook
debian/tmp/usr/share/doc/tde/HTML/en/ark/man-ark.1.docbook
debian/tmp/usr/share/icons/hicolor/128x128/apps/ark.png
debian/tmp/usr/share/icons/hicolor/16x16/apps/ark.png
debian/tmp/usr/share/icons/hicolor/22x22/apps/ark.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/ark.png
debian/tmp/usr/share/icons/hicolor/48x48/apps/ark.png
debian/tmp/usr/share/icons/hicolor/64x64/apps/ark.png
debian/tmp/usr/share/icons/hicolor/scalable/apps/ark.svgz
debian/tmp/usr/share/man/man1/ark.1
debian/tmp/usr/share/services/ark_part.desktop

debian/icons/ark.xpm		/usr/share/pixmaps
debian/icons/ark-16.xpm		/usr/share/pixmaps
