debian/tmp/usr/bin/kcalc
debian/tmp/usr/lib/*/trinity/kcalc.la
debian/tmp/usr/lib/*/trinity/kcalc.so
debian/tmp/usr/lib/*/libtdeinit_kcalc.so
debian/tmp/usr/share/applications/tde/kcalc.desktop
debian/tmp/usr/share/apps/kcalc/kcalcui.rc
debian/tmp/usr/share/apps/tdeconf_update/kcalcrc.upd
debian/tmp/usr/share/config.kcfg/kcalc.kcfg
debian/tmp/usr/share/doc/tde/HTML/en/kcalc/common
debian/tmp/usr/share/doc/tde/HTML/en/kcalc/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/kcalc/index.docbook
debian/tmp/usr/share/doc/tde/HTML/en/kcalc/commands.docbook
#debian/tmp/usr/share/doc/tde/HTML/en/kcalc/kcalc_on_Aix.txt
#debian/tmp/usr/share/doc/tde/HTML/en/kcalc/kcalc_on_OSF.txt
debian/tmp/usr/share/icons/hicolor/16x16/apps/kcalc.png
debian/tmp/usr/share/icons/hicolor/22x22/apps/kcalc.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/kcalc.png
debian/tmp/usr/share/icons/hicolor/48x48/apps/kcalc.png
debian/tmp/usr/share/icons/hicolor/64x64/apps/kcalc.png
debian/tmp/usr/share/icons/hicolor/scalable/apps/kcalc.svgz
debian/tmp/usr/share/man/man1/kcalc.1

debian/icons/kcalc.xpm		/usr/share/pixmaps
debian/icons/kcalc-16.xpm	/usr/share/pixmaps
