debian/tmp/usr/bin/kdf
debian/tmp/usr/bin/kwikdisk
debian/tmp/usr/lib/*/trinity/kcm_kdf.la
debian/tmp/usr/lib/*/trinity/kcm_kdf.so
debian/tmp/usr/share/applications/tde/kcmdf.desktop
debian/tmp/usr/share/applications/tde/kdf.desktop
debian/tmp/usr/share/applications/tde/kwikdisk.desktop
debian/tmp/usr/share/apps/kdf/kdfui.rc
debian/tmp/usr/share/apps/kdf/pics/delete.png
debian/tmp/usr/share/apps/kdf/pics/tick.png
debian/tmp/usr/share/doc/tde/HTML/en/kdf/common
debian/tmp/usr/share/doc/tde/HTML/en/kdf/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/kdf/index.docbook
debian/tmp/usr/share/doc/tde/HTML/en/kdf/kdf.png
debian/tmp/usr/share/doc/tde/HTML/en/kdf/kdf_config.png
debian/tmp/usr/share/doc/tde/HTML/en/kcontrol/storagedevices/common
debian/tmp/usr/share/doc/tde/HTML/en/kcontrol/storagedevices/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/kcontrol/storagedevices/index.docbook
debian/tmp/usr/share/icons/hicolor/128x128/apps/kdf.png
debian/tmp/usr/share/icons/hicolor/128x128/apps/kwikdisk.png
debian/tmp/usr/share/icons/hicolor/16x16/apps/kdf.png
debian/tmp/usr/share/icons/hicolor/16x16/apps/kwikdisk.png
debian/tmp/usr/share/icons/hicolor/22x22/apps/kdf.png
debian/tmp/usr/share/icons/hicolor/22x22/apps/kwikdisk.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/kdf.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/kwikdisk.png
debian/tmp/usr/share/icons/hicolor/48x48/apps/kdf.png
debian/tmp/usr/share/icons/hicolor/48x48/apps/kwikdisk.png
debian/tmp/usr/share/icons/hicolor/64x64/apps/kdf.png
debian/tmp/usr/share/icons/hicolor/64x64/apps/kwikdisk.png
debian/tmp/usr/share/man/man1/kdf.1
debian/tmp/usr/share/man/man1/kwikdisk.1

debian/icons/kdf.xpm		/usr/share/pixmaps
debian/icons/kdf-16.xpm		/usr/share/pixmaps
debian/icons/kwikdisk.xpm	/usr/share/pixmaps
debian/icons/kwikdisk-16.xpm	/usr/share/pixmaps
