debian/tmp/usr/bin/khexedit
debian/tmp/usr/lib/*/trinity/libkbyteseditwidget.la
debian/tmp/usr/lib/*/trinity/libkbyteseditwidget.so
debian/tmp/usr/lib/*/trinity/libkhexedit2part.la
debian/tmp/usr/lib/*/trinity/libkhexedit2part.so
debian/tmp/usr/lib/*/libkhexeditcommon.so.0
debian/tmp/usr/lib/*/libkhexeditcommon.so.0.0.0
debian/tmp/usr/share/applications/tde/khexedit.desktop
debian/tmp/usr/share/apps/khexedit/khexeditui.rc
debian/tmp/usr/share/apps/khexedit/pics/hexdrag.png
debian/tmp/usr/share/apps/khexedit/pics/hexmask.png
debian/tmp/usr/share/apps/khexedit/pics/hexwrite.png
debian/tmp/usr/share/apps/khexedit2part/khexedit2partui.rc
debian/tmp/usr/share/doc/tde/HTML/en/khexedit/common
debian/tmp/usr/share/doc/tde/HTML/en/khexedit/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/khexedit/index.docbook
debian/tmp/usr/share/doc/tde/HTML/en/khexedit/khexedit1.png
debian/tmp/usr/share/icons/hicolor/16x16/apps/khexedit.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/khexedit.png
debian/tmp/usr/share/icons/hicolor/48x48/apps/khexedit.png
debian/tmp/usr/share/man/man1/khexedit.1
debian/tmp/usr/share/services/kbyteseditwidget.desktop
debian/tmp/usr/share/services/khexedit2part.desktop

debian/icons/khexedit.xpm		/usr/share/pixmaps
debian/icons/khexedit-16.xpm		/usr/share/pixmaps
