debian/tmp/usr/bin/kjots
debian/tmp/usr/share/applications/tde/Kjots.desktop
debian/tmp/usr/share/apps/kjots/kjotsui.rc
debian/tmp/usr/share/apps/kjots/pics/filedel.png
debian/tmp/usr/share/config.kcfg/kjots.kcfg
debian/tmp/usr/share/doc/tde/HTML/en/kjots/common
debian/tmp/usr/share/doc/tde/HTML/en/kjots/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/kjots/index.docbook
debian/tmp/usr/share/icons/hicolor/16x16/apps/kjots.png
debian/tmp/usr/share/icons/hicolor/22x22/apps/kjots.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/kjots.png
debian/tmp/usr/share/icons/hicolor/48x48/apps/kjots.png
debian/tmp/usr/share/icons/hicolor/64x64/apps/kjots.png

debian/icons/kjots.xpm		/usr/share/pixmaps
debian/icons/kjots-16.xpm	/usr/share/pixmaps
