debian/tmp/usr/bin/kdict
debian/tmp/usr/lib/*/trinity/kdict.la
debian/tmp/usr/lib/*/trinity/kdict.so
debian/tmp/usr/lib/*/trinity/kdict_panelapplet.la
debian/tmp/usr/lib/*/trinity/kdict_panelapplet.so
debian/tmp/usr/lib/*/libtdeinit_kdict.so
debian/tmp/usr/share/applications/tde/kdict.desktop
debian/tmp/usr/share/apps/kdict/icons/crystalsvg/16x16/actions/define_clip.png
debian/tmp/usr/share/apps/kdict/icons/crystalsvg/16x16/actions/query_erase.png
debian/tmp/usr/share/apps/kdict/icons/crystalsvg/22x22/actions/define_clip.png
debian/tmp/usr/share/apps/kdict/icons/crystalsvg/32x32/actions/define_clip.png
debian/tmp/usr/share/apps/kdict/kdictui.rc
debian/tmp/usr/share/apps/kicker/applets/kdictapplet.desktop
debian/tmp/usr/share/doc/tde/HTML/en/kdict/applet.png
debian/tmp/usr/share/doc/tde/HTML/en/kdict/common
debian/tmp/usr/share/doc/tde/HTML/en/kdict/conf.png
debian/tmp/usr/share/doc/tde/HTML/en/kdict/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/kdict/index.docbook
debian/tmp/usr/share/doc/tde/HTML/en/kdict/mainwin.png
debian/tmp/usr/share/doc/tde/HTML/en/kdict/seteditor.png
debian/tmp/usr/share/icons/hicolor/128x128/apps/kdict.png
debian/tmp/usr/share/icons/hicolor/16x16/apps/kdict.png
debian/tmp/usr/share/icons/hicolor/32x32/apps/kdict.png
debian/tmp/usr/share/icons/hicolor/48x48/apps/kdict.png
debian/tmp/usr/share/icons/hicolor/64x64/apps/kdict.png
debian/tmp/usr/share/icons/hicolor/scalable/apps/kdict.svgz
debian/tmp/usr/share/man/man1/kdict.1

debian/icons/kdict-16.xpm	/usr/share/pixmaps
debian/icons/kdict.xpm		/usr/share/pixmaps
