debian/tmp/usr/bin/krfb
debian/tmp/usr/bin/krfb_httpd
debian/tmp/usr/lib/*/trinity/kcm_krfb.la
debian/tmp/usr/lib/*/trinity/kcm_krfb.so
debian/tmp/usr/lib/*/trinity/kded_kinetd.la
debian/tmp/usr/lib/*/trinity/kded_kinetd.so
debian/tmp/usr/share/applications/tde/kcmkrfb.desktop
debian/tmp/usr/share/applications/tde/krfb.desktop
debian/tmp/usr/share/apps/kinetd/eventsrc
debian/tmp/usr/share/apps/krfb/eventsrc
debian/tmp/usr/share/apps/krfb/pics/connection-side-image.png
debian/tmp/usr/share/apps/krfb/pics/eyes-closed24.png
debian/tmp/usr/share/apps/krfb/pics/eyes-open24.png
debian/tmp/usr/share/doc/tde/HTML/en/krfb/common
debian/tmp/usr/share/doc/tde/HTML/en/krfb/configuration_access.png
debian/tmp/usr/share/doc/tde/HTML/en/krfb/configuration_network.png
debian/tmp/usr/share/doc/tde/HTML/en/krfb/configuration_session.png
debian/tmp/usr/share/doc/tde/HTML/en/krfb/connection.png
debian/tmp/usr/share/doc/tde/HTML/en/krfb/email_invitation.png
debian/tmp/usr/share/doc/tde/HTML/en/krfb/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/krfb/index.docbook
debian/tmp/usr/share/doc/tde/HTML/en/krfb/invitation_management.png
debian/tmp/usr/share/doc/tde/HTML/en/krfb/personal_invitation.png
debian/tmp/usr/share/doc/tde/HTML/en/krfb/screenshot.png
debian/tmp/usr/share/icons/crystalsvg/16x16/apps/krfb.png
debian/tmp/usr/share/icons/crystalsvg/32x32/apps/krfb.png
debian/tmp/usr/share/icons/crystalsvg/48x48/apps/krfb.png
debian/tmp/usr/share/icons/locolor/16x16/apps/krfb.png
debian/tmp/usr/share/icons/locolor/32x32/apps/krfb.png
debian/tmp/usr/share/services/kded/kinetd.desktop
debian/tmp/usr/share/services/kinetd_krfb.desktop
debian/tmp/usr/share/services/kinetd_krfb_httpd.desktop
debian/tmp/usr/share/servicetypes/kinetdmodule.desktop

debian/icons/krfb-16.xpm	/usr/share/pixmaps
debian/icons/krfb.xpm		/usr/share/pixmaps
