debian/tmp/usr/lib/*/trinity/kcm_lanbrowser.la
debian/tmp/usr/lib/*/trinity/kcm_lanbrowser.so
debian/tmp/usr/lib/*/trinity/tdeio_lan.la
debian/tmp/usr/lib/*/trinity/tdeio_lan.so
debian/tmp/usr/share/applnk/.hidden/kcmtdeiolan.desktop
debian/tmp/usr/share/applnk/.hidden/kcmlisa.desktop
debian/tmp/usr/share/applnk/.hidden/kcmreslisa.desktop
debian/tmp/usr/share/apps/konqsidebartng/virtual_folders/services/lisa.desktop
debian/tmp/usr/share/apps/konqueror/dirtree/remote/lan.desktop
debian/tmp/usr/share/apps/lisa/README
debian/tmp/usr/share/apps/remoteview/lan.desktop
debian/tmp/usr/share/doc/tde/HTML/en/kcontrol/lanbrowser/common
debian/tmp/usr/share/doc/tde/HTML/en/kcontrol/lanbrowser/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/kcontrol/lanbrowser/index.docbook
debian/tmp/usr/share/doc/tde/HTML/en/lisa/common
debian/tmp/usr/share/doc/tde/HTML/en/lisa/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/lisa/index.docbook
debian/tmp/usr/share/man/man8/lisa.8
debian/tmp/usr/share/man/man8/reslisa.8
debian/tmp/usr/share/services/lan.protocol
debian/tmp/usr/share/services/rlan.protocol

debian/lisarc		etc/
debian/tmp/usr/bin/lisa		usr/sbin/
debian/tmp/usr/bin/reslisa	usr/sbin/
