debian/tmp/opt/trinity/bin/
debian/tmp/opt/trinity/lib/*.so*
debian/tmp/opt/trinity/lib/*.la
debian/tmp/opt/trinity/share/servicetypes/
debian/tmp/opt/trinity/share/applications/
debian/tmp/opt/trinity/share/apps/kaffeine/
debian/tmp/opt/trinity/share/apps/profiles/kaffeine.profile.xml
debian/tmp/opt/trinity/share/apps/konqueror/servicemenus/kaffeine_open_directory.desktop
debian/tmp/opt/trinity/share/apps/konqueror/servicemenus/kaffeine_append_file.desktop
debian/tmp/opt/trinity/share/apps/konqueror/servicemenus/kaffeine_play_dvd.desktop
debian/tmp/opt/trinity/share/apps/konqueror/servicemenus/kaffeine_play_vcd.desktop
debian/tmp/opt/trinity/share/doc/
debian/tmp/opt/trinity/share/icons/
debian/tmp/opt/trinity/share/mimelnk/application/x-kaffeine.desktop
debian/tmp/opt/trinity/share/locale/
debian/tmp/opt/trinity/include/kaffeine/*h
debian/tmp/opt/trinity/share/man/man1/kaffeine.1
debian/tmp/opt/trinity/share/services/kaffeinemp3lame.desktop
debian/tmp/opt/trinity/share/services/kaffeineoggvorbis.desktop
debian/tmp/opt/trinity/lib/trinity/libkaffeinemp3lame.la
debian/tmp/opt/trinity/lib/trinity/libkaffeinemp3lame.so
debian/tmp/opt/trinity/lib/trinity/libkaffeineoggvorbis.la
debian/tmp/opt/trinity/lib/trinity/libkaffeineoggvorbis.so
debian/tmp/opt/trinity/lib/trinity/libxinepart.la
debian/tmp/opt/trinity/lib/trinity/libxinepart.so
debian/tmp/opt/trinity/share/services/xine_part.desktop

debian/kaffeine.xpm /opt/trinity/share/pixmaps
