debian/tmp/usr/bin/adddebug
debian/tmp/usr/bin/build-progress.sh
debian/tmp/usr/bin/cheatmake
debian/tmp/usr/bin/create_cvsignore
debian/tmp/usr/bin/create_makefile
debian/tmp/usr/bin/create_makefiles
debian/tmp/usr/bin/cvs-clean
debian/tmp/usr/bin/cvs2dist
debian/tmp/usr/bin/cvsbackport
debian/tmp/usr/bin/cvsblame
debian/tmp/usr/bin/cvscheck
debian/tmp/usr/bin/cvsforwardport
debian/tmp/usr/bin/cvslastchange
debian/tmp/usr/bin/cvslastlog
debian/tmp/usr/bin/cvsrevertlast
debian/tmp/usr/bin/cvsversion
debian/tmp/usr/bin/cxxmetric
debian/tmp/usr/bin/extend_dmalloc
debian/tmp/usr/bin/extractattr
debian/tmp/usr/bin/extractrc
debian/tmp/usr/bin/findmissingcrystal
debian/tmp/usr/bin/fixkdeincludes
debian/tmp/usr/bin/fixuifiles
debian/tmp/usr/bin/includemocs
debian/tmp/usr/bin/kde-build
debian/tmp/usr/bin/kdedoc
debian/tmp/usr/bin/tdekillall
debian/tmp/usr/bin/kdelnk2desktop.py
debian/tmp/usr/bin/kdemangen.pl
debian/tmp/usr/bin/makeobj
debian/tmp/usr/bin/noncvslist
debian/tmp/usr/bin/package_crystalsvg
debian/tmp/usr/bin/png2mng.pl
debian/tmp/usr/bin/pruneemptydirs
debian/tmp/usr/bin/qtdoc
debian/tmp/usr/bin/zonetab2pot.py
debian/tmp/usr/bin/svn2dist
debian/tmp/usr/bin/svnrevertlast
debian/tmp/usr/bin/svnforwardport
debian/tmp/usr/bin/nonsvnlist
debian/tmp/usr/bin/tdesvn-build
debian/tmp/usr/bin/svnlastlog
debian/tmp/usr/bin/svnversions
debian/tmp/usr/bin/create_svnignore
debian/tmp/usr/bin/svnlastchange
debian/tmp/usr/bin/colorsvn
debian/tmp/usr/bin/svnaddcurrentdir
debian/tmp/usr/bin/svnbackport
debian/tmp/usr/bin/svngettags
debian/tmp/usr/bin/svnchangesince
debian/tmp/usr/bin/svn-clean
debian/tmp/usr/share/apps/katepart/syntax/tdesvn-buildrc.xml
debian/tmp/usr/share/doc/tde/HTML/en/tdesvn-build/common
debian/tmp/usr/share/doc/tde/HTML/en/tdesvn-build/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/tdesvn-build/index.docbook

debian/tmp/usr/share/man/man1/cvsblame.1
debian/tmp/usr/share/man/man1/cvsversion.1
debian/tmp/usr/share/man/man1/includemocs.1
debian/tmp/usr/share/man/man1/kde-build.1
debian/tmp/usr/share/man/man1/noncvslist.1
debian/tmp/usr/share/man/man1/tdesvn-build.1

debian/tmp/usr/share/man/man1/adddebug.1
debian/tmp/usr/share/man/man1/build-progress.sh.1
debian/tmp/usr/share/man/man1/cheatmake.1
debian/tmp/usr/share/man/man1/create_cvsignore.1
debian/tmp/usr/share/man/man1/create_makefile.1
debian/tmp/usr/share/man/man1/create_makefiles.1
debian/tmp/usr/share/man/man1/cvs-clean.1
debian/tmp/usr/share/man/man1/cvs2dist.1
debian/tmp/usr/share/man/man1/cvsbackport.1
debian/tmp/usr/share/man/man1/cvscheck.1
debian/tmp/usr/share/man/man1/cvsforwardport.1
debian/tmp/usr/share/man/man1/cvslastchange.1
debian/tmp/usr/share/man/man1/cvslastlog.1
debian/tmp/usr/share/man/man1/cvsrevertlast.1
debian/tmp/usr/share/man/man1/cxxmetric.1
debian/tmp/usr/share/man/man1/extend_dmalloc.1
debian/tmp/usr/share/man/man1/extractattr.1
debian/tmp/usr/share/man/man1/extractrc.1
debian/tmp/usr/share/man/man1/findmissingcrystal.1
debian/tmp/usr/share/man/man1/fixkdeincludes.1
debian/tmp/usr/share/man/man1/fixuifiles.1
debian/tmp/usr/share/man/man1/kdedoc.1
debian/tmp/usr/share/man/man1/kdelnk2desktop.py.1
debian/tmp/usr/share/man/man1/kdemangen.pl.1
debian/tmp/usr/share/man/man1/makeobj.1
debian/tmp/usr/share/man/man1/package_crystalsvg.1
debian/tmp/usr/share/man/man1/png2mng.pl.1
debian/tmp/usr/share/man/man1/pruneemptydirs.1
debian/tmp/usr/share/man/man1/qtdoc.1
debian/tmp/usr/share/man/man1/tdekillall.1
debian/tmp/usr/share/man/man1/zonetab2pot.py.1
scripts/kde-devel-gdb /usr/share/tdesdk-scripts
scripts/kde-devel-vim.vim /usr/share/tdesdk-scripts
scripts/kde-emacs/*.el /usr/share/emacs/site-lisp/tdesdk-scripts
scripts/kde.supp /usr/lib/valgrind
scripts/completions /usr/share/tdesdk-scripts

debian/desktop-i18n/createdesktop.pl /usr/lib/kubuntu-desktop-i18n/
debian/desktop-i18n/findfiles /usr/lib/kubuntu-desktop-i18n/
debian/desktop-i18n/msgsplit /usr/lib/kubuntu-desktop-i18n/

