debian/tmp/usr/bin/kfind
debian/tmp/usr/lib/*/trinity/libkfindpart.la
debian/tmp/usr/lib/*/trinity/libkfindpart.so
debian/tmp/usr/share/applications/tde/Kfind.desktop
debian/tmp/usr/share/apps/kfindpart/icons/locolor/22x22/actions/archive.png
debian/tmp/usr/share/apps/kfindpart/icons/locolor/22x22/actions/delete.png
debian/tmp/usr/share/apps/kfindpart/icons/locolor/22x22/actions/idea.png
debian/tmp/usr/share/apps/kfindpart/icons/locolor/22x22/actions/info.png
debian/tmp/usr/share/apps/kfindpart/icons/locolor/22x22/actions/openfile.png
debian/tmp/usr/share/apps/kfindpart/icons/locolor/22x22/actions/save.png
debian/tmp/usr/share/apps/kfindpart/icons/locolor/22x22/actions/search.png
debian/tmp/usr/share/doc/tde/HTML/en/kfind/common
debian/tmp/usr/share/doc/tde/HTML/en/kfind/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/kfind/index.docbook
debian/tmp/usr/share/icons/hicolor/*/apps/kfind.png
debian/tmp/usr/share/man/man1/kfind.1
debian/tmp/usr/share/services/kfindpart.desktop
debian/tmp/usr/share/servicetypes/findpart.desktop

debian/icons/kfind.xpm		/usr/share/pixmaps
debian/icons/kfind-16.xpm	/usr/share/pixmaps
