debian/tmp/usr/bin/kpm
debian/tmp/usr/bin/ksysguard
debian/tmp/usr/lib/*/trinity/sysguard_panelapplet.la
debian/tmp/usr/lib/*/trinity/sysguard_panelapplet.so
debian/tmp/usr/lib/*/libksgrd.so.1
debian/tmp/usr/lib/*/libksgrd.so.1.2.0
debian/tmp/usr/share/applications/tde/ksysguard.desktop
debian/tmp/usr/share/apps/kicker/applets/ksysguardapplet.desktop
debian/tmp/usr/share/apps/ksysguard/eventsrc
debian/tmp/usr/share/apps/ksysguard/KSysGuardApplet.xml
debian/tmp/usr/share/apps/ksysguard/ksysguardui.rc
debian/tmp/usr/share/apps/ksysguard/pics/computer.png
debian/tmp/usr/share/apps/ksysguard/pics/daemon.png
debian/tmp/usr/share/apps/ksysguard/pics/kernel.png
debian/tmp/usr/share/apps/ksysguard/pics/ksysguardd.png
debian/tmp/usr/share/apps/ksysguard/pics/running.png
debian/tmp/usr/share/apps/ksysguard/pics/shell.png
debian/tmp/usr/share/apps/ksysguard/pics/tdeapp.png
debian/tmp/usr/share/apps/ksysguard/pics/tools.png
debian/tmp/usr/share/apps/ksysguard/pics/unknownapp.png
debian/tmp/usr/share/apps/ksysguard/pics/waiting.png
debian/tmp/usr/share/apps/ksysguard/pics/X.png
debian/tmp/usr/share/apps/ksysguard/ProcessTable.sgrd
debian/tmp/usr/share/apps/ksysguard/SystemLoad.sgrd
debian/tmp/usr/share/doc/tde/HTML/en/ksysguard/common
debian/tmp/usr/share/doc/tde/HTML/en/ksysguard/index.cache.bz2
debian/tmp/usr/share/doc/tde/HTML/en/ksysguard/index.docbook
debian/tmp/usr/share/icons/crystalsvg/*/apps/ksysguard.png
debian/tmp/usr/share/mimelnk/application/x-ksysguard.desktop

debian/icons/ksysguard.xpm		/usr/share/pixmaps
debian/icons/ksysguard-16.xpm		/usr/share/pixmaps
