debian/tmp/usr/bin/ktip
debian/tmp/usr/share/applications/tde/ktip.desktop
debian/tmp/usr/share/applnk/Toys/ktip.desktop
debian/tmp/usr/share/apps/tdewizard/pics/wizard_small.png
debian/tmp/usr/share/apps/tdewizard/tips
debian/tmp/usr/share/autostart/ktip.desktop
debian/tmp/usr/share/icons/hicolor/*/apps/ktip.png
debian/tmp/usr/share/icons/hicolor/scalable/apps/ktip.svgz

debian/icons/ktip.xpm		/usr/share/pixmaps
debian/icons/ktip-16.xpm	/usr/share/pixmaps
